[workspace]
authors = ["Ethan Marquez <ethanhmarquez@gmail.com>"]
channels = ["conda-forge"]
name = "M-star-analysis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
register-kernel = "python -m ipykernel install --user --name astro-pixi --display-name 'Python (astro-pixi)'"

[dependencies]
python = ">=3.12,<3.13"

[pypi-dependencies]
ipykernel = "*"
mesa_reader = "*"
matplotlib = "*"
numpy = "*"
